# Generated by Django 5.1 on 2024-09-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='has_cafe',
            field=models.BooleanField(default=False),
        ),
    ]
